services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - dream-team-network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 3s
      timeout: 1s
      retries: 10
    
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: hackathon_db
    ports:
      - "3306:3306"
    networks:
      - dream-team-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD}"]
      interval: 2s
      timeout: 1s
      retries: 5

  hrdirector:
    build:
      context: . 
      dockerfile: ./HRDirectorService/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - ./TeamLeads.csv:/app/TeamLeads.csv
      - ./Juniors.csv:/app/Juniors.csv
    ports:
      - "8000:8000"
    networks:
      - dream-team-network

  hrmanager:
    build:
      context: . 
      dockerfile: ./HRManagerService/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - ./TeamLeads.csv:/app/TeamLeads.csv
      - ./Juniors.csv:/app/Juniors.csv
    networks:
      - dream-team-network

  junior1:
    build:
      context: .
      dockerfile: ./ParticipantService/Dockerfile
    environment:
      PARTICIPANT_ID: 1
      PARTICIPANT_NAME: "Юдин Адам"
      PARTICIPANT_ROLE: "Junior"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - dream-team-network
    volumes:
      - ./TeamLeads.csv:/app/TeamLeads.csv
      - ./Juniors.csv:/app/Juniors.csv

  junior2:
    build:
      context: . 
      dockerfile: ./ParticipantService/Dockerfile
    environment:
      PARTICIPANT_ID: 2
      PARTICIPANT_NAME: "Яшина Яна"
      PARTICIPANT_ROLE: "Junior"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - dream-team-network
    volumes:
      - ./TeamLeads.csv:/app/TeamLeads.csv
      - ./Juniors.csv:/app/Juniors.csv

  junior3:
    build:
      context: . 
      dockerfile: ./ParticipantService/Dockerfile
    environment:
      PARTICIPANT_ID: 3
      PARTICIPANT_NAME: "Никитина Вероника"
      PARTICIPANT_ROLE: "Junior"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - dream-team-network
    volumes:
      - ./TeamLeads.csv:/app/TeamLeads.csv
      - ./Juniors.csv:/app/Juniors.csv

  junior4:
    build:
      context: . 
      dockerfile: ./ParticipantService/Dockerfile
    environment:
      PARTICIPANT_ID: 4
      PARTICIPANT_NAME: "Рябинин Александр"
      PARTICIPANT_ROLE: "Junior"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - dream-team-network
    volumes:
      - ./TeamLeads.csv:/app/TeamLeads.csv
      - ./Juniors.csv:/app/Juniors.csv

  junior5:
    build:
      context: . 
      dockerfile: ./ParticipantService/Dockerfile
    environment:
      PARTICIPANT_ID: 5
      PARTICIPANT_NAME: "Ильин Тимофей"
      PARTICIPANT_ROLE: "Junior"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - dream-team-network
    volumes:
      - ./TeamLeads.csv:/app/TeamLeads.csv
      - ./Juniors.csv:/app/Juniors.csv

  teamplead1:
    build:
      context: . 
      dockerfile: ./ParticipantService/Dockerfile
    environment:
      PARTICIPANT_ID: 6
      PARTICIPANT_NAME: "Филиппова Ульяна"
      PARTICIPANT_ROLE: "TeamLead"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - dream-team-network
    volumes:
      - ./TeamLeads.csv:/app/TeamLeads.csv
      - ./Juniors.csv:/app/Juniors.csv

  teamplead2:
    build:
      context: . 
      dockerfile: ./ParticipantService/Dockerfile
    environment:
      PARTICIPANT_ID: 7
      PARTICIPANT_NAME: "Николаев Григорий"
      PARTICIPANT_ROLE: "TeamLead"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - dream-team-network
    volumes:
      - ./TeamLeads.csv:/app/TeamLeads.csv
      - ./Juniors.csv:/app/Juniors.csv

  teamplead3:
    build:
      context: . 
      dockerfile: ./ParticipantService/Dockerfile
    environment:
      PARTICIPANT_ID: 8
      PARTICIPANT_NAME: "Андреева Вероника"
      PARTICIPANT_ROLE: "TeamLead"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - dream-team-network
    volumes:
      - ./TeamLeads.csv:/app/TeamLeads.csv
      - ./Juniors.csv:/app/Juniors.csv

  teamplead4:
    build:
      context: . 
      dockerfile: ./ParticipantService/Dockerfile
    environment:
      PARTICIPANT_ID: 9
      PARTICIPANT_NAME: "Коротков Михаил"
      PARTICIPANT_ROLE: "TeamLead"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - dream-team-network
    volumes:
      - ./TeamLeads.csv:/app/TeamLeads.csv
      - ./Juniors.csv:/app/Juniors.csv

  teamplead5:
    build:
      context: . 
      dockerfile: ./ParticipantService/Dockerfile
    environment:
      PARTICIPANT_ID: 10
      PARTICIPANT_NAME: "Кузнецов Александр"
      PARTICIPANT_ROLE: "TeamLead"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - dream-team-network
    volumes:
      - ./TeamLeads.csv:/app/TeamLeads.csv
      - ./Juniors.csv:/app/Juniors.csv

networks:
  dream-team-network:
    driver: bridge

# volumes:
#   mysql_data: